apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-order-dpl
  labels:
    app: k8s-order
spec:
  selector:
    matchLabels:
      app: k8s-order
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-order
    spec:
      containers:
      - name: k8s-order-containers
        image: hoangduc02011998/k8s-go-grpc-order:v1
        ports:
        - name: order-service
          containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: k8s-order
  ports:
  - port: 3000
    targetPort: order-service      